DEFINE_ACTION_FUNCTION debug_quickstart BEGIN

	ACTION_IF is_iwd BEGIN

		// IWD start
		COPY_EXISTING "ar1006.bcs" override
			DECOMPILE_AND_PATCH BEGIN
				REPLACE_TEXTUALLY ~StartCutScene.*~ ""
				REPLACE_TEXTUALLY ~IncrementChapter.*~ ""
			END
		BUT_ONLY
		// HoW start
		LAF DELETE_SCRIPT_BLOCK STR_VAR script=ar9100 match=HOW_SEER_MOV END
		
	END
	
	ACTION_IF is_bg2 BEGIN
	
		// SoA start

	
	END

END