DEFINE_ACTION_FUNCTION modified_priest_strongholds BEGIN

			// shared setup
			LAF run STR_VAR file=cleric_strongholds location=stronghold locbase=kit END
			// actually activate it
			
			ACTION_FOR_EACH dialog IN bharval bhoisig bhnalla BEGIN
				COPY_EXISTING "%dialog%.dlg" override
					DECOMPILE_AND_PATCH BEGIN
						REPLACE_TEXTUALLY EXACT_MATCH ~Global("dw_block_this","GLOBAL",1)~ ~~
					END
			END

















END