DEFINE_ACTION_FUNCTION make_int_payload BEGIN


	// get splprot entry
	LAF resolve_splprot_entry INT_VAR stat=38 value="-1" STR_VAR relation=equal RET splprot_value=value END

	// master spell
	
	CREATE spl "dw3eint"
		LPF add_basic_spell_ability END
		FOR (value=minimum_bonus_spell_abil;value<=25;value+=1) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode=321 target=2 STR_VAR resource="dw3em%value%" END
			LPF ADD_SPELL_EFFECT INT_VAR opcode=326 target=2 parameter1=value parameter2=splprot_value STR_VAR resource="dw3em%value%" END
		END

END
