DEFINE_ACTION_FUNCTION test STR_VAR version=0 BEGIN



	cre.copy[es8erth=>%cre_ice_elemental_8hd% elearpr=>%cre_ice_elemental_12hd% elearpr2=>%cre_ice_elemental_16hd% elearpr3=>%cre_ice_elemental_24hd%]
	[
		m_animation:=GOLEM_ICE
		m_resist_cold=100
		m_resist_fire="-50"
		m.cre_strip_scripts{%baf_earth_elemental%}
		m.cre_insert_script{%baf_ice_elemental%|loc=high}
		m.fx.delete{}
		m.cre_remove_spells{all}
		PATCH_IF m_level1>=16 BEGIN
			m.cre_add_spells{%spl_ice_elemental_ice_storm%}
		END			
		m.immunity_spell{%WIZARD_ICE_STORM%}
		m.immunity_spell{%spl_ice_elemental_ice_storm%}
	]

END
